version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Use `production` for production deployment
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password123@db/dfm_db
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload & sleep 10; python /app/db/load_data.py; wait"


  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: dfm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db" ]
      interval: 10s
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
